
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mambocoto
 */
public class BReportes extends javax.swing.JFrame {
    public BReportes() {
        initComponents();
        llenarTable();
        this.Bank=Bank.selfCargar();
        ImageIcon logo= new ImageIcon(this.Bank.getImage());
        this.LBanco.setText(this.Bank.getNombre());
        logo.setImage(logo.getImage().getScaledInstance(250, 125, Image.SCALE_SMOOTH));
        BLogo.setIcon(logo);
        RHora.setSelected(true);      
    }
    public void llenarTable(){
        this.Lreportes.readList().ToString();
        this.Lreportes=this.Lreportes.readList();
        this.Lreportes.moveToFirst();
        DefaultTableModel modelo= (DefaultTableModel)TablaDinamica.getModel();
        String [] fila=new String[5*this.Lreportes.getSize()];
        System.out.println(this.Lreportes.getSize()+" != "+0);
        
        for(int j=0;this.Lreportes.getSize()!=j;j++){
            for (int i=0;i!=fila.length;i+=5){
             fila[i]=this.Lreportes.getDataActual().getNombre(); 
        
             fila[i+1]=this.Lreportes.getDataActual().getCorreo();
        
             fila[i+2]=this.Lreportes.getDataActual().horaAtendido();
             
             fila[i+3]=this.Lreportes.getDataActual().fechaAtendido();
            
             fila[i+4]=this.Lreportes.getDataActual().getTipo();
            }
            this.Lreportes.moveNext();
            modelo.addRow(fila);
        } 
        TablaDinamica.setAutoResizeMode(TablaDinamica.getAutoResizeMode());
        TablaDinamica.setModel(modelo);
    }
    public void eliminarTable(){
        DefaultTableModel modelo= (DefaultTableModel)this.TablaDinamica.getModel();
        System.out.println("BORRANDOOOOOOOOO");
        for(int i=0;i!=modelo.getRowCount();i+=0){
            System.out.println("BORRANDO"+i+"NUMERO DE FILAS    "+modelo.getRowCount());
            modelo.removeRow(i);
        }
        this.TablaDinamica.setModel(modelo);
    }
    public void llenarTable(Lista Lreportes){
        Lreportes.readList().ToString();
        Lreportes.moveToFirst();
        DefaultTableModel modelo= (DefaultTableModel)TablaDinamica.getModel();
        String [] fila=new String[5*this.Lreportes.getSize()];
        
        for(int j=0;Lreportes.getSize()!=j;j++){
            for (int i=0;i!=fila.length;i+=5){
             fila[i]=Lreportes.getDataActual().getNombre(); 
             
             fila[i+1]=Lreportes.getDataActual().getCorreo();
        
             fila[i+2]=Lreportes.getDataActual().horaAtendido();
            
             fila[i+3]=Lreportes.getDataActual().fechaAtendido();
        
             fila[i+4]=Lreportes.getDataActual().getTipo();  
             
            }
            Lreportes.moveNext();
            modelo.addRow(fila);
        } 
        TablaDinamica.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoOrdenamiento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        TablaDinamica = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        RHora = new javax.swing.JRadioButton();
        RFecha = new javax.swing.JRadioButton();
        RPriory = new javax.swing.JRadioButton();
        BLogo = new javax.swing.JLabel();
        LBanco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 133, 28));

        TablaDinamica.setFont(new java.awt.Font("Liberation Serif", 2, 15)); // NOI18N
        TablaDinamica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Hora", "Fecha", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(TablaDinamica);

        jRadioButton1.setBackground(new java.awt.Color(238, 133, 28));
        TipoOrdenamiento.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(243, 229, 229));
        jRadioButton1.setText("Nombre");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(238, 133, 28));
        TipoOrdenamiento.add(jRadioButton2);
        jRadioButton2.setText("Correo");
        jRadioButton2.setFocusPainted(false);

        RHora.setBackground(new java.awt.Color(238, 133, 28));
        TipoOrdenamiento.add(RHora);
        RHora.setText("Hora");
        RHora.setFocusPainted(false);

        RFecha.setBackground(new java.awt.Color(238, 133, 28));
        TipoOrdenamiento.add(RFecha);
        RFecha.setText("Fecha");
        RFecha.setFocusPainted(false);
        RFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFechaActionPerformed(evt);
            }
        });

        RPriory.setBackground(new java.awt.Color(238, 133, 28));
        TipoOrdenamiento.add(RPriory);
        RPriory.setText("Prioridad");
        RPriory.setFocusPainted(false);
        RPriory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPrioryActionPerformed(evt);
            }
        });

        BLogo.setBackground(new java.awt.Color(243, 131, 19));
        BLogo.setText("jLabel1");

        LBanco.setFont(new java.awt.Font("Liberation Serif", 3, 36)); // NOI18N
        LBanco.setForeground(new java.awt.Color(249, 239, 239));
        LBanco.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 243, 243));
        jLabel1.setText("Lista de Clientes ordenada por:");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(1, 1, 1)
                        .addComponent(RHora)
                        .addGap(63, 63, 63)
                        .addComponent(RFecha)
                        .addGap(52, 52, 52)
                        .addComponent(RPriory)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(RHora)
                    .addComponent(RFecha)
                    .addComponent(RPriory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void RPrioryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPrioryActionPerformed
        this.Lreportes.bubbleSort();
        this.eliminarTable();
        this.llenarTable(Lreportes);
    }//GEN-LAST:event_RPrioryActionPerformed

    private void RFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFechaActionPerformed
       this.Lreportes.readList();
       this.eliminarTable();
       this.llenarTable();
    }//GEN-LAST:event_RFechaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    Lista Lreportes=new Lista();
    Banco Bank= new Banco();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BLogo;
    private javax.swing.JLabel LBanco;
    private javax.swing.JRadioButton RFecha;
    private javax.swing.JRadioButton RHora;
    private javax.swing.JRadioButton RPriory;
    private javax.swing.JTable TablaDinamica;
    private javax.swing.ButtonGroup TipoOrdenamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
