/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;
import java.util.Locale;
import javax.swing.JOptionPane;
import org.jfree.chart.*;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.*;
import org.jfree.data.xy.*;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Carlos Ramirez
 */
public class Graficas extends javax.swing.JFrame {

    /**
     * Creates new form Graficas
     */
    public Graficas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Lineas.setVisible(false);
        this.Barras.setVisible(false);
        this.Pastel.setVisible(false);
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        l = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        p = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CAPAS = new javax.swing.JLayeredPane();
        Lineas = new javax.swing.JPanel();
        Barras = new javax.swing.JPanel();
        Pastel = new javax.swing.JPanel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(datos);

        l.setText("Lineas");
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        b.setText("Barras");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        p.setText("Pastel");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Grafico");

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CAPAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout LineasLayout = new javax.swing.GroupLayout(Lineas);
        Lineas.setLayout(LineasLayout);
        LineasLayout.setHorizontalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        LineasLayout.setVerticalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarrasLayout = new javax.swing.GroupLayout(Barras);
        Barras.setLayout(BarrasLayout);
        BarrasLayout.setHorizontalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        BarrasLayout.setVerticalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PastelLayout = new javax.swing.GroupLayout(Pastel);
        Pastel.setLayout(PastelLayout);
        PastelLayout.setHorizontalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        PastelLayout.setVerticalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CAPASLayout = new javax.swing.GroupLayout(CAPAS);
        CAPAS.setLayout(CAPASLayout);
        CAPASLayout.setHorizontalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CAPASLayout.setVerticalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        CAPAS.setLayer(Lineas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Barras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Pastel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(l)
                                .addGap(18, 18, 18)
                                .addComponent(b)
                                .addGap(10, 10, 10)
                                .addComponent(p)))
                        .addGap(18, 18, 18)
                        .addComponent(CAPAS)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l)
                            .addComponent(b)
                            .addComponent(p))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(CAPAS))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        Lineas.setVisible(true);
        CAPAS.setLayer(Lineas,0,0);
        b.setSelected(false);
        p.setSelected(false);
        
    }//GEN-LAST:event_lActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        Barras.setVisible(true);
        CAPAS.setLayer(Barras,0,0);
        l.setSelected(false);
        p.setSelected(false);
    }//GEN-LAST:event_bActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        Pastel.setVisible(true);
        CAPAS.setLayer(Pastel,0,0);
        b.setSelected(false);
        l.setSelected(false);
    }//GEN-LAST:event_pActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChartPanel panel;
        JFreeChart chart=null;
        
        if(l.isSelected()){
           //grafico lineas
            int validar=1;
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            
            XYSeries serie = new XYSeries ("Datos");
            
            XYPlot plot;
            Lineas.removeAll();
            
            try{
                for (int fila=0;fila<4;fila++){
                    serie.add(Float.parseFloat(String.valueOf(datos.getValueAt(fila,0))),
                            Float.parseFloat(String.valueOf(datos.getValueAt(fila,1))));
                    
                }
        }catch(Exception ex){
            validar=0;
        }
        if (validar==1){
            dataset.addSeries(serie);
            x.setLabel("Eje X");
            y.setLabel("Eje Y");
            plot = new XYPlot(dataset,x,y,renderer);
            chart = new JFreeChart (plot);
            chart.setTitle("Grafico de Lineas");
           
        }else{
            JOptionPane.showMessageDialog(this,"Debe llenar la tabla con datos numericos");
            
        }
        
       }else{
           if(b.isSelected()){
               //Grafico de Barras
               DefaultCategoryDataset data = new DefaultCategoryDataset();
               String producto1 ="Sopas";
               String producto2 ="Soda";
               
               String dia1 ="Dia 1";
               String dia2 ="Dia 2";
               String dia3 ="Dia 3";
               String dia4 ="Dia 4";
               
               data.addValue(18,producto1,dia1);
               data.addValue(15,producto1,dia2);
               data.addValue(14,producto1,dia3);
               data.addValue(11,producto1,dia4);
               
               data.addValue(20,producto2,dia1);
               data.addValue(22,producto2,dia2);
               data.addValue(10,producto2,dia3);
               data.addValue(25,producto2,dia4);
               
               chart = ChartFactory.createBarChart("Grafico de Barras","Dias","Cantidad",
                       data,
                       PlotOrientation.HORIZONTAL,
                       true,
                       true,
                       true);
               CategoryPlot plot = (CategoryPlot) chart.getPlot();
               plot.setDomainGridlinesVisible(true);
               
           }else{
               //grafico de Pastel
               DefaultPieDataset data = new DefaultPieDataset();
               data.setValue("Categoria 1",20);
               data.setValue("Categoria 2",60);
               data.setValue("Categoria 3",20);
               
               //chart = ChartFactory.createPieChart3D("Grafico de Pastel",data, true,true,true);
               chart = ChartFactory.createPieChart("Grafico de Pastel",data, true,true,true);
               
           }
       }
        panel= new ChartPanel(chart);
        panel.setBounds(5,10,400,350);
        
        if(l.isSelected()){
            Lineas.add(panel);
            Lineas.repaint();
        }else{
            if(b.isSelected()){
                Barras.add(panel);
                Barras.repaint();
            }else{
                Pastel.add(panel);
                Pastel.repaint();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barras;
    private javax.swing.JLayeredPane CAPAS;
    private javax.swing.JPanel Lineas;
    private javax.swing.JPanel Pastel;
    private javax.swing.JRadioButton b;
    private javax.swing.JTable datos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton l;
    private javax.swing.JRadioButton p;
    // End of variables declaration//GEN-END:variables
}
