/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.SpinnerModel;
import org.jfree.chart.*;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Carlos Ramirez
 */
public class Graficas extends javax.swing.JFrame {
    Dia actual;
    int especial,mayor,embarazada,regular,corporativo;
    /**
     * Creates new form Graficas
     * @param graficar
     * Ingresa con el dia seleccionado
     */
    public Graficas(Dia graficar) {
        actual=graficar;
        initComponents();
        this.setLocationRelativeTo(null);
        this.Barras.setVisible(false);
        this.Pastel.setVisible(false);
        this.jCorp.setText(jCorp.getText()+" "+Integer.toString(this.actual.getCorporativos()));
        this.jEmba.setText(jEmba.getText()+" "+Integer.toString(this.actual.getEmbrazadas()));
        this.jAmayor.setText(jAmayor.getText()+" "+Integer.toString(this.actual.getAmayor()));
        this.jregular.setText(jregular.getText()+" "+Integer.toString(this.actual.getRegulares()));
        this.jespeciales.setText(jespeciales.getText()+" "+Integer.toString(this.actual.getEspecial()));
        this.Jtotal.setText(Jtotal.getText()+" "+Integer.toString(this.actual.getTotal()));
        this.horaFin.setVisible(false);
        this.horaIni.setVisible(false);
        this.jFin.setVisible(false);
        this.jIni.setVisible(false);
        //numero = new SpinnerModel();
                
       // this.horaFin.setModel();
                /*data.addValue(this.actual.getEspecial(),categoria1,categoria1);
               data.addValue(this.actual.getAmayor(),categoria2,categoria2);
               data.addValue(this.actual.getEmbrazadas(),categoria3,categoria3);
               data.addValue(this.actual.getCorporativos(),categoria4,categoria4);
               data.addValue(this.actual.getRegulares(),categoria5,categoria5);*/        

        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        b = new javax.swing.JRadioButton();
        p = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CAPAS = new javax.swing.JLayeredPane();
        Lineas = new javax.swing.JPanel();
        Barras = new javax.swing.JPanel();
        Pastel = new javax.swing.JPanel();
        ComboDia = new javax.swing.JComboBox();
        jespeciales = new javax.swing.JLabel();
        jAmayor = new javax.swing.JLabel();
        jEmba = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCorp = new javax.swing.JLabel();
        jregular = new javax.swing.JLabel();
        Jtotal = new javax.swing.JLabel();
        horaIni = new javax.swing.JSpinner();
        horaFin = new javax.swing.JSpinner();
        jFin = new javax.swing.JLabel();
        jIni = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grafico");

        b.setText("Barras");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        p.setText("Pastel");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Grafico");

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CAPAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout LineasLayout = new javax.swing.GroupLayout(Lineas);
        Lineas.setLayout(LineasLayout);
        LineasLayout.setHorizontalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        LineasLayout.setVerticalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarrasLayout = new javax.swing.GroupLayout(Barras);
        Barras.setLayout(BarrasLayout);
        BarrasLayout.setHorizontalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        BarrasLayout.setVerticalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PastelLayout = new javax.swing.GroupLayout(Pastel);
        Pastel.setLayout(PastelLayout);
        PastelLayout.setHorizontalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        PastelLayout.setVerticalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CAPASLayout = new javax.swing.GroupLayout(CAPAS);
        CAPAS.setLayout(CAPASLayout);
        CAPASLayout.setHorizontalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CAPASLayout.setVerticalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        CAPAS.setLayer(Lineas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Barras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Pastel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ComboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "Hora" }));
        ComboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDiaActionPerformed(evt);
            }
        });

        jespeciales.setText("Cliente Especiales:");

        jAmayor.setText("Adulto mayor:");

        jEmba.setText("Embarazada:");

        jCorp.setText("C. Corporativo:");

        jregular.setText("C. Regular:");

        Jtotal.setText("Total:");

        horaIni.setModel(new javax.swing.SpinnerNumberModel(1, 0, 24, 1));

        horaFin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jFin.setText("Hora de Fin");

        jIni.setText("Hora de inicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jIni)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jFin))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(p))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(b)
                                        .addGap(116, 116, 116))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jespeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEmba, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCorp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jregular, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(horaFin)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(horaIni)))
                .addGap(18, 18, 18)
                .addComponent(CAPAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jIni)
                        .addGap(18, 18, 18)
                        .addComponent(jFin)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(horaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p)
                    .addComponent(b, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jespeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAmayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jregular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAPAS)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        Barras.setVisible(true);
        CAPAS.setLayer(Barras,0,0);
        p.setSelected(false);
    }//GEN-LAST:event_bActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        Pastel.setVisible(true);
        CAPAS.setLayer(Pastel,0,0);
        b.setSelected(false);
        
    }//GEN-LAST:event_pActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChartPanel panel;
        JFreeChart chart=null;
        //especial,mayor,embarazada,regular,corporativo
       // ComboDia.getSelectedItem()
        if(ComboDia.getSelectedIndex()==0){
            System.out.println("Funca");
        especial=this.actual.getEspecial();
        mayor=this.actual.getAmayor();
        embarazada=this.actual.getEmbrazadas();
        corporativo=this.actual.getCorporativos();
        regular=this.actual.getRegulares();
        }else{
        especial=this.actual.horavshoraES((int)this.horaFin.getValue(), (int)this.horaIni.getValue());
        mayor=this.actual.horavshoraAM((int)this.horaFin.getValue(), (int)this.horaIni.getValue());
        embarazada=this.actual.horavshoraEM((int)this.horaFin.getValue(), (int)this.horaIni.getValue());
        corporativo=this.actual.horavshoraCO((int)this.horaFin.getValue(), (int)this.horaIni.getValue());
        regular=this.actual.horavshoraRE((int)this.horaFin.getValue(), (int)this.horaIni.getValue());
        }
        {
        
           if(b.isSelected()){
               //Grafico de Barras
               DefaultCategoryDataset data = new DefaultCategoryDataset();
               
               String categoria1 ="Especiales";
               String categoria2 ="A.Mayor";
               String categoria3 ="Embarazadas";
               String categoria4 ="Corporativo";
               String categoria5 ="Regulares";
               
               data.addValue(especial,categoria1,categoria1);
               data.addValue(mayor,categoria2,categoria2);
               data.addValue(embarazada,categoria3,categoria3);
               data.addValue(this.corporativo,categoria4,categoria4);
               data.addValue(this.regular,categoria5,categoria5);
               
               
               chart = ChartFactory.createBarChart("Grafico de Barras","Tipo de Cliente","Cantidad",
                       data,
                       PlotOrientation.VERTICAL,
                       true,
                       true,
                       true);
               CategoryPlot plot = (CategoryPlot) chart.getPlot();
               plot.setDomainGridlinesVisible(true);
               
           }else{
               //grafico de Pastel
               DefaultPieDataset data = new DefaultPieDataset();
               data.setValue("Especial",this.especial);
               data.setValue("A.Mayor",this.mayor);
               data.setValue("Embarazadas",this.embarazada);
               data.setValue("Corporativas",this.corporativo);
               data.setValue("Regulares",this.regular);
               
               //chart = ChartFactory.createPieChart3D("Grafico de Pastel",data, true,true,true);
               chart = ChartFactory.createPieChart("Grafico de Pastel",data, true,true,true);
               
           }
       }
        panel= new ChartPanel(chart);
        panel.setBounds(5,10,400,350);
        
        
            if(b.isSelected()){
                Barras.add(panel);
                Barras.repaint();
            }else{
                Pastel.add(panel);
                Pastel.repaint();
        }
        //new Graficas().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDiaActionPerformed
        if(this.ComboDia.getSelectedIndex()==1){
        this.horaFin.setVisible(true);
        this.horaIni.setVisible(true);
        this.jFin.setVisible(true);
        this.jIni.setVisible(true);
        }
        else{
        this.horaFin.setVisible(false);
        this.horaIni.setVisible(false);
        this.jFin.setVisible(false);
        this.jIni.setVisible(false);
        }
    }//GEN-LAST:event_ComboDiaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barras;
    private javax.swing.JLayeredPane CAPAS;
    private javax.swing.JComboBox ComboDia;
    private javax.swing.JLabel Jtotal;
    private javax.swing.JPanel Lineas;
    private javax.swing.JPanel Pastel;
    private javax.swing.JRadioButton b;
    private javax.swing.JSpinner horaFin;
    private javax.swing.JSpinner horaIni;
    private javax.swing.JLabel jAmayor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCorp;
    private javax.swing.JLabel jEmba;
    private javax.swing.JLabel jFin;
    private javax.swing.JLabel jIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jespeciales;
    private javax.swing.JLabel jregular;
    private javax.swing.JRadioButton p;
    // End of variables declaration//GEN-END:variables
}
