/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import org.jfree.chart.*;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Carlos Ramirez
 */
public class Graficas extends javax.swing.JFrame {
    Dia actual;
    /**
     * Creates new form Graficas
     */
    public Graficas(Dia graficar) {
        actual=graficar;
        initComponents();
        this.setLocationRelativeTo(null);
        this.Barras.setVisible(false);
        this.Pastel.setVisible(false);
        this.jCorp.setText(jCorp.getText()+" "+Integer.toString(this.actual.getCorporativos()));
        this.jEmba.setText(jEmba.getText()+" "+Integer.toString(this.actual.getEmbrazadas()));
        this.jAmayor.setText(jAmayor.getText()+" "+Integer.toString(this.actual.getAmayor()));
        this.jregular.setText(jregular.getText()+" "+Integer.toString(this.actual.getRegulares()));
        this.jespeciales.setText(jespeciales.getText()+" "+Integer.toString(this.actual.getEspecial()));
        this.Jtotal.setText(Jtotal.getText()+" "+Integer.toString(this.actual.getTotal()));
                /*data.addValue(this.actual.getEspecial(),categoria1,categoria1);
               data.addValue(this.actual.getAmayor(),categoria2,categoria2);
               data.addValue(this.actual.getEmbrazadas(),categoria3,categoria3);
               data.addValue(this.actual.getCorporativos(),categoria4,categoria4);
               data.addValue(this.actual.getRegulares(),categoria5,categoria5);*/        

        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        b = new javax.swing.JRadioButton();
        p = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CAPAS = new javax.swing.JLayeredPane();
        Lineas = new javax.swing.JPanel();
        Barras = new javax.swing.JPanel();
        Pastel = new javax.swing.JPanel();
        ComboDia = new javax.swing.JComboBox();
        jespeciales = new javax.swing.JLabel();
        jAmayor = new javax.swing.JLabel();
        jEmba = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCorp = new javax.swing.JLabel();
        jregular = new javax.swing.JLabel();
        Jtotal = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grafico");

        b.setText("Barras");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        p.setText("Pastel");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Grafico");

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CAPAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout LineasLayout = new javax.swing.GroupLayout(Lineas);
        Lineas.setLayout(LineasLayout);
        LineasLayout.setHorizontalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        LineasLayout.setVerticalGroup(
            LineasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BarrasLayout = new javax.swing.GroupLayout(Barras);
        Barras.setLayout(BarrasLayout);
        BarrasLayout.setHorizontalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        BarrasLayout.setVerticalGroup(
            BarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PastelLayout = new javax.swing.GroupLayout(Pastel);
        Pastel.setLayout(PastelLayout);
        PastelLayout.setHorizontalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        PastelLayout.setVerticalGroup(
            PastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CAPASLayout = new javax.swing.GroupLayout(CAPAS);
        CAPAS.setLayout(CAPASLayout);
        CAPASLayout.setHorizontalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CAPASLayout.setVerticalGroup(
            CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(Barras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(CAPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CAPASLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(Pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        CAPAS.setLayer(Lineas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Barras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CAPAS.setLayer(Pastel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ComboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "Hora" }));

        jespeciales.setText("Cliente Especiales:");

        jAmayor.setText("Adulto mayor:");

        jEmba.setText("Embarazada:");

        jCorp.setText("C. Corporativo:");

        jregular.setText("C. Regular:");

        Jtotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p))
                                    .addComponent(ComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jespeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmba, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCorp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jregular, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(CAPAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b)
                    .addComponent(p))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jespeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAmayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCorp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jregular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAPAS)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        Barras.setVisible(true);
        CAPAS.setLayer(Barras,0,0);
        p.setSelected(false);
    }//GEN-LAST:event_bActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        Pastel.setVisible(true);
        CAPAS.setLayer(Pastel,0,0);
        b.setSelected(false);
        
    }//GEN-LAST:event_pActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChartPanel panel;
        JFreeChart chart=null;
       // ComboDia.getSelectedItem()
        {
           if(b.isSelected()){
               //Grafico de Barras
               DefaultCategoryDataset data = new DefaultCategoryDataset();
               
               String categoria1 ="Especiales";
               String categoria2 ="A.Mayor";
               String categoria3 ="Embarazadas";
               String categoria4 ="Corporativo";
               String categoria5 ="Regulares";
               
               data.addValue(this.actual.getEspecial(),categoria1,categoria1);
               data.addValue(this.actual.getAmayor(),categoria2,categoria2);
               data.addValue(this.actual.getEmbrazadas(),categoria3,categoria3);
               data.addValue(this.actual.getCorporativos(),categoria4,categoria4);
               data.addValue(this.actual.getRegulares(),categoria5,categoria5);
               
               
               chart = ChartFactory.createBarChart("Grafico de Barras","Tipo de Cliente","Cantidad",
                       data,
                       PlotOrientation.VERTICAL,
                       true,
                       true,
                       true);
               CategoryPlot plot = (CategoryPlot) chart.getPlot();
               plot.setDomainGridlinesVisible(true);
               
           }else{
               //grafico de Pastel
               DefaultPieDataset data = new DefaultPieDataset();
               data.setValue("Especial",this.actual.getEspecial());
               data.setValue("A.Mayor",this.actual.getAmayor());
               data.setValue("Embarazadas",this.actual.getEmbrazadas());
               data.setValue("Corporativas",this.actual.getCorporativos());
               data.setValue("Regulares",this.actual.getRegulares());
               
               //chart = ChartFactory.createPieChart3D("Grafico de Pastel",data, true,true,true);
               chart = ChartFactory.createPieChart("Grafico de Pastel",data, true,true,true);
               
           }
       }
        panel= new ChartPanel(chart);
        panel.setBounds(5,10,400,350);
        
        
            if(b.isSelected()){
                Barras.add(panel);
                Barras.repaint();
            }else{
                Pastel.add(panel);
                Pastel.repaint();
        }
        //new Graficas().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barras;
    private javax.swing.JLayeredPane CAPAS;
    private javax.swing.JComboBox ComboDia;
    private javax.swing.JLabel Jtotal;
    private javax.swing.JPanel Lineas;
    private javax.swing.JPanel Pastel;
    private javax.swing.JRadioButton b;
    private javax.swing.JLabel jAmayor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCorp;
    private javax.swing.JLabel jEmba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jespeciales;
    private javax.swing.JLabel jregular;
    private javax.swing.JRadioButton p;
    // End of variables declaration//GEN-END:variables
}
